# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  pod 'FirebaseCore'
  pod 'FirebaseMessaging'

  project 'iosApp.xcodeproj'

end
