# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '13.0'

target 'iosApp' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
